"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabaseClient";

type Company = { id:string; name:string; city:string|null; status:string; package_name:string|null; subscription_ends_at:string|null; created_at:string };
export default function AdminPage(){
 const [companies,setCompanies]=useState<Company[]>([]); const [authorized,setAuthorized]=useState(false); const [loading,setLoading]=useState(true);
 async function loadCompanies(){ const {data:userData}=await supabase.auth.getUser(); if(!userData.user){window.location.href="/login";return;} const {data:profile}=await supabase.from("profiles").select("role").eq("id",userData.user.id).single(); if(profile?.role!=="admin"){window.location.href="/dashboard";return;} setAuthorized(true); const {data}=await supabase.from("companies").select("*").order("created_at",{ascending:false}); setCompanies(data??[]); setLoading(false); }
 useEffect(()=>{loadCompanies();},[]);
 async function updateStatus(companyId:string,status:string){ await supabase.from("companies").update({status}).eq("id",companyId); loadCompanies(); }
 async function logout(){ await supabase.auth.signOut(); window.location.href="/login"; }
 const activeCount=companies.filter(c=>c.status==="active").length; const demoCount=companies.filter(c=>c.status==="demo").length; const passiveCount=companies.filter(c=>c.status==="passive").length;
 if(loading) return <main className="loading-page">AYÇA Panel yükleniyor...</main>; if(!authorized) return null;
 return <main className="panel-page"><aside className="sidebar"><div className="sidebar-logo">AYÇA</div><a className="active">Yönetici Paneli</a><a href="/dashboard">Müşteri Paneli</a><button onClick={logout}>Çıkış Yap</button></aside><section className="panel-content"><div className="panel-header"><div><span className="muted">AYÇA Yönetim</span><h1>Yönetici Dashboard</h1><p>Müşteri, paket ve demo erişimlerini buradan takip edeceğiz.</p></div></div><div className="metric-grid"><div className="metric-card"><span>Toplam Müşteri</span><strong>{companies.length}</strong></div><div className="metric-card"><span>Aktif</span><strong>{activeCount}</strong></div><div className="metric-card"><span>Demo</span><strong>{demoCount}</strong></div><div className="metric-card"><span>Pasif</span><strong>{passiveCount}</strong></div></div><div className="table-card"><div className="table-title"><h2>Müşteriler</h2><span>{companies.length} kayıt</span></div><div className="responsive-table"><table><thead><tr><th>Müşteri</th><th>Şehir</th><th>Paket</th><th>Durum</th><th>Bitiş</th><th>İşlem</th></tr></thead><tbody>{companies.map(company=><tr key={company.id}><td>{company.name}</td><td>{company.city??"-"}</td><td>{company.package_name??"Demo"}</td><td><span className={"status "+company.status}>{company.status}</span></td><td>{company.subscription_ends_at??"-"}</td><td className="table-actions"><button onClick={()=>updateStatus(company.id,"active")}>Aktif</button><button onClick={()=>updateStatus(company.id,"demo")}>Demo</button><button onClick={()=>updateStatus(company.id,"passive")}>Pasif</button></td></tr>)}</tbody></table></div></div></section></main>;
}
